all:
	npm install && cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build && cd ../node_modules/broker-simulator-rnymphaea/backend && npm install && npm run build && cd ../frontend && npm install && npm run build

admin-frontend:
	cd node_modules/broker-simulator-rnymphaea/frontend && npm run start

admin-backend:
	cd node_modules/broker-simulator-rnymphaea/backend && npm run start

